### ISSUE TITLE
lib_temporary() less useful than expected

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgman#11]
```
pkgman::lib_temporary()
.libPaths()
#> [1] "/private/tmp/RtmpFue9UC/library-5d2022749503"                  
#> [2] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library"

pkgman::pkg_install("purrr", num_workers = 2)
#> Error in loadNamespace(name) : there is no package called ‘pkgdepends’
```

It's not clear this is a bug, but it does seem less useful than I had hoped.

**Comment by jimhester** [comment]
Yeah, maybe `lib_activate()` should have a default action of `prepend` rather than `replace`, or `lib_temporary()` should...

**Comment by gaborcsardi** [comment]
Personally, I would prefer some more comprehensive support for project libraries. E.g. automatically using a local library, it is exists. (Unless configured otherwise.) We can have a standard name for project libraries, and then easily exclude them from git and the potential local R package.

I think it would be great if the user could avoid manipulating libraries manually, by just having sensible defaults: a local project library, a user library for common stuff like `devtools` and the R base (+recommended?) library.

One  hard part is setting up these libraries, because you cannot put a non-existing directory in `.libPaths()` (very annoying!).

**Comment by hadley** [comment]
If it does prepend, is there some way to tel `pkg_install()` not to look for packages further about the library path? The semantics get complicated.

`lib_activate()` should probably always create the directory if it doesn't exist.

**Comment by jimhester** [comment]
I am pretty sure `pkgdepends` only looks in one library directory for its resolution currently, and we only pass it the first library in `.libPaths()` anyway.

**Comment by gaborcsardi** [comment]
We think this will be solved by https://github.com/r-lib/pkginstall/issues/4
